spring.application.name=secureuserauth

# server.address=0.0.0.0


# --- Banco de dados H2 persistente ---
spring.datasource.url=jdbc:h2:file:./data/secureuserauth
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# --- Console H2 (opcional) ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console